### ISSUE TITLE
Refactor: should export as static site for embedding to media-server binary

### ISSUE THREAD

**Issue by giangndm** [8xFF/atm0s-media-server-console#4]
For easier using, we should build this console as static site for embedding to media-server binary directly.

Currently when I try to generate static build it show error:

```
pnpm build

> console@0.1.0 build /Users/giangminh/Workspace/8xff/dev/atm0s-media-server-console/apps/console
> next build

  ▲ Next.js 14.2.4

   Creating an optimized production build ...
 ✓ Compiled successfully
 ✓ Linting and checking validity of types

> Build error occurred
Error: Page "/zones/[id]" is missing "generateStaticParams()" so it cannot be used with "output: export" config.
```

**Comment by caohv** [comment]
> For easier using, we should build this console as static site for embedding to media-server binary directly.
> 
> Currently when I try to generate static build it show error:
> 
> ```
> pnpm build
> 
> > console@0.1.0 build /Users/giangminh/Workspace/8xff/dev/atm0s-media-server-console/apps/console
> > next build
> 
>   ▲ Next.js 14.2.4
> 
>    Creating an optimized production build ...
>  ✓ Compiled successfully
>  ✓ Linting and checking validity of types
> 
> > Build error occurred
> Error: Page "/zones/[id]" is missing "generateStaticParams()" so it cannot be used with "output: export" config.
> ```

The problem you are facing is because the current code does not support creating static pages
